// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerManagementService.Data;

#nullable disable

namespace PlayerManagementService.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20241212033727_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerManagementService.Models.Players", b =>
                {
                    b.Property<int>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playerId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("playerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            playerId = 1,
                            IsAvailable = true,
                            Name = "Player One"
                        },
                        new
                        {
                            playerId = 2,
                            IsAvailable = true,
                            Name = "Player Two"
                        },
                        new
                        {
                            playerId = 3,
                            IsAvailable = true,
                            Name = "Player Three"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
